# Generated by Django 3.1 on 2020-08-08 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='story',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
