# Generated by Django 3.1 on 2020-08-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200808_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoArchive',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.todo')),
            ],
            bases=('todo.todo',),
        ),
    ]
