# Generated by Django 3.1 on 2020-08-26 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todoarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoarchive',
            name='date_archived',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
