# Generated by Django 2.1.15 on 2020-09-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200827_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
    ]
