# Generated by Django 2.1.15 on 2020-09-01 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20200901_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoarchive',
            name='todo_ptr',
        ),
        migrations.AddField(
            model_name='todo',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TodoArchive',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_archived',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
