# Generated by Django 2.1.15 on 2020-09-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20200901_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_archived',
        ),
    ]
